version: '3'
services:
  mock-premier-league:
    container_name: mock-premier-league
    restart: always
    build: .
    ports:
      - "8080:3500"
    links:
      - mock-premier-league-redis
      - mock-premier-league-mongo
    volumes:
      - .:/usr/src/mock-premier-league
    depends_on:
      - mongodb
      - redis
  mongo:
    container_name: mock-premier-league-mongo
    image: 'mongo'
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE= mock_premier_league
  redis:
    container_name: mock-premier-league-redis
    image: 'redis:4.0.11'
    ports:
      - "6379:6379"
    volumes: 
      - ./data:/data/cache
    restart: unless-stopped

